2024-12-14 06:46:06,247 INFO    MainThread:9658 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-14 06:46:06,248 INFO    MainThread:9658 [wandb_setup.py:_flush():68] Configure stats pid to 9658
2024-12-14 06:46:06,248 INFO    MainThread:9658 [wandb_setup.py:_flush():68] Loading settings from /app/.config/wandb/settings
2024-12-14 06:46:06,248 INFO    MainThread:9658 [wandb_setup.py:_flush():68] Loading settings from /root/app/wandb/settings
2024-12-14 06:46:06,248 INFO    MainThread:9658 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-14 06:46:06,248 INFO    MainThread:9658 [wandb_init.py:_log_setup():528] Logging user logs to /root/app/wandb/run-20241214_064606-k65t44cl/logs/debug.log
2024-12-14 06:46:06,249 INFO    MainThread:9658 [wandb_init.py:_log_setup():529] Logging internal logs to /root/app/wandb/run-20241214_064606-k65t44cl/logs/debug-internal.log
2024-12-14 06:46:06,249 INFO    MainThread:9658 [wandb_init.py:init():644] calling init triggers
2024-12-14 06:46:06,249 INFO    MainThread:9658 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2024-12-14 06:46:06,249 INFO    MainThread:9658 [wandb_init.py:init():680] starting backend
2024-12-14 06:46:06,249 INFO    MainThread:9658 [wandb_init.py:init():684] sending inform_init request
2024-12-14 06:46:06,301 INFO    MainThread:9658 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-14 06:46:06,302 INFO    MainThread:9658 [wandb_init.py:init():697] backend started and connected
2024-12-14 06:46:06,303 INFO    MainThread:9658 [wandb_init.py:init():790] updated telemetry
2024-12-14 06:46:06,325 WARNING MsgRouterThr:9658 [router.py:message_loop():75] message_loop has been closed
2024-12-14 06:46:06,368 INFO    MainThread:9658 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2024-12-14 06:46:11,370 ERROR   MainThread:9658 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/root/app/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "/root/app/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/app/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
